apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: external-dns
spec:
  destination:
    name: homelab
    namespace: external-dns
  project: core-utilities
  source:
    path: external-dns
    repoURL: https://github.com/salineselin/kube-monorepo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
