apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smarter-device-manager
  namespace: argocd
spec:
  destination:
    name: homelab
  project: default
  source:
    path: smarter-device-manager
    repoURL: https://github.com/salineselin/kube-monorepo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
