apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: minecraft
  project: default
  source:
    path: minecraft/homelab
    repoURL: https://github.com/salineselin/k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
