apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: rook
  project: default
  source:
    path: deploy/examples
    repoURL: https://github.com/rook/rook
    targetRevision: v1.11.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
