apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vintagestory
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: vintagestory
  project: default
  source:
    path: vintagestory
    repoURL: https://github.com/salineselin/k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
