apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30303
      name: qbittorrent
  selector:
    app: qbittorrent
