apiVersion: v1
kind: Service
metadata:
  name: nfs
  namespace: nfs
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs
  clusterIP: 10.43.12.13
