kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bree-n-me-minecraft-pvc
  namespace: bree-n-me-minecraft
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
