apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gcp-dns
  namespace: cert-manager
spec:
  acme:
    email: salineselin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: nuggies-life
    solvers:
      - dns01:
          cloudDNS:
            project: elite-protocol-319303
