apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  serviceName: minecraft-svc
  replicas: 1
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: "itzg/minecraft-server:latest"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 512m
              memory: 4096Mi
            limits:
              cpu: 1024m
              memory: 8192Mi
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: minecraft-cm
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: minecraft-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minecraft-pvc
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
