apiVersion: v1
kind: ConfigMap
metadata:
  name: element-configmap-config
  namespace: maholit-club-web
data:
  config: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "https://maholit.club",
          "server_name": "maholit.club"
        }
      },
      "brand": "Element",
      "integrations_ui_url": "",
      "integrations_rest_url": "",
      "integrations_widgets_urls": [],
      "default_country_code": "US",
      "show_labs_settings": false,
      "default_theme": "dark"
    }
