apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maholit-club-web

resources:
  - namespace.yml
  - element-deployment.yml
  - element-service.yml
  - element-ingress.yml
  - element-configmap.yml
  - synapse-deployment.yml
  - synapse-service.yml
  - synapse-configmap-log-config.yml
  - synapse-secret-config.yml
  - synapse-secret-signingkey.yml
  - synapse-volume-media.yml
