apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vintagestory
  namespace: vintagestory
  labels:
    app: vintagestory
spec:
  serviceName: vintagestory-svc
  replicas: 1
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: vintagestory
  template:
    metadata:
      labels:
        app: vintagestory
    spec:
      containers:
        - name: vintagestory
          image: "ich777/vintagestory"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 512m
              memory: 4gi
            limits:
              cpu: 1024m
              memory: 24gi
          readinessProbe:
            tcpSocket:
              port: 42420
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 42420
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: vintagestory-cm
          ports:
            - name: vintagestory
              containerPort: 42420
              protocol: TCP
          volumeMounts:
            - name: vintagestory-pvc
              mountPath: /vintagestory/data
  volumeClaimTemplates:
    - metadata:
        name: vintagestory-pvc
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
