apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

bases:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml
# patches:
# - path: transformations/container-arguments.yml
#   target:
#     group: apps
#     kind: Deployment
#     name: external-dns
# - path: transformations/security-context.yml
#   target:
#     group: apps
#     kind: Deployment
#     name: external-dns
