apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
  - additions/ingress.yml
  - additions/backendConfig.yml
  - additions/frontendConfig.yml

namespace: argocd

patches:
  - path: transformations/modify-server-service.yml
    target:
      kind: Service
      name: argocd-server
  - path: transformations/enable-server-insecure.yml
    target:
      group: apps
      kind: Deployment
      name: argocd-server
  - path: transformations/add-account.yml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: transformations/map-rbac.yml
    target:
      kind: ConfigMap
      name: argocd-cm
