apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
  - additions/namespace.yaml

namespace: argocd

patches:
  - path: transformations/add-account.yml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: transformations/map-rbac.yml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
