apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-gcp-dns
    networking.gke.io/v1beta1.FrontendConfig: argocd-frontend-config
spec:
  ingressClassName: gce
  rules:
    - host: argocd.salinesel.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
  tls:
    - hosts:
        - argocd.salinesel.in
      secretName: argocd-secret
