apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: jellyfin-env
          ports:
            - containerPort: 8096
              protocol: TCP
          volumeMounts:
            - name: jellyfin
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: jellyfin
          nfs:
            server: 10.43.12.13 # icky but necessary for nfs to work. cannot reference dns name
            path: /jellyfin
