apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: jellyfin
spec:
  type: LoadBalancer
  ports:
    - port: 8096
      targetPort: 8096
      name: jellyfin
  selector:
    app: jellyfin
