apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bree-n-me-minecraft

bases:
  - additions/namespace.yml
  - additions/pvc.yml
  - additions/service.yml
  - additions/statefulset.yml
