apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
    - port: 42069
      targetPort: 25565
      name: minecraft
  selector:
    app: minecraft
