apiVersion: v1
kind: Service
metadata:
  name: bree-n-me-minecraft
  namespace: bree-n-me-minecraft
  labels:
    app: bree-n-me-minecraft
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft.nuggies.life
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 42069
      targetPort: 25565
      name: minecraft
  selector:
    app: bree-n-me-minecraft
