apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

bases:
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/kustomize/external-dns-clusterrole.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/kustomize/external-dns-clusterrolebinding.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/kustomize/external-dns-deployment.yaml
  - additions/namespace.yml
  - additions/service-account.yml

patches:
  - path: transformations/container-arguments.yml
    target:
      group: apps
      kind: Deployment
      name: external-dns
  - path: transformations/security-context.yml
    target:
      group: apps
      kind: Deployment
      name: external-dns
