apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    helm.sh/chart: external-dns-1.20.0
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.20.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: release-name
  ports:
    - name: http
      port: 7979
      targetPort: http
      protocol: TCP
    - name: http-webhook
      port: 8080
      targetPort: http-webhook
      protocol: TCP
