apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
  - additions/cluster-issuer-gcp-dns-staging.yml
  - additions/cluster-issuer-gcp-dns.yml

patchesStrategicMerge:
  - additions/workload-identity-annotation.yml

patches:
  - path: transformations/enable-ambient-credentials.yml
    target:
      group: apps
      kind: Deployment
      name: cert-manager
